# GENERATED by `make codegen` from packages/scenespec/scenespec.schema.json (D7).
# Do not edit. CI fails if this file is stale.

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Vec3Item(RootModel[float]):
    root: float = Field(..., ge=-1000.0, le=1000.0)


class Vec3(RootModel[list[Vec3Item]]):
    root: list[Vec3Item] = Field(..., max_length=3, min_length=3)


class Vec2Item(RootModel[float]):
    root: float = Field(..., ge=-1000.0, le=1000.0)


class Vec2(RootModel[list[Vec2Item]]):
    root: list[Vec2Item] = Field(..., max_length=2, min_length=2)


class PartId(RootModel[str]):
    root: str = Field(..., pattern="^[a-z0-9_]{1,48}$")


class HexColor(RootModel[str]):
    root: str = Field(
        ..., description="Colors are hex only (spec §4).", pattern="^#[0-9a-fA-F]{6}$"
    )


class Sphere(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["sphere"]
    radius: float = Field(..., gt=0.0, le=100.0)


class Box(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["box"]
    w: float = Field(..., gt=0.0, le=100.0)
    h: float = Field(..., gt=0.0, le=100.0)
    d: float = Field(..., gt=0.0, le=100.0)


class Cylinder(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["cylinder"]
    r_top: float = Field(..., ge=0.0, le=100.0)
    r_bottom: float = Field(..., ge=0.0, le=100.0)
    height: float = Field(..., gt=0.0, le=100.0)
    open_ended: bool | None = False


class Cone(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["cone"]
    radius: float = Field(..., gt=0.0, le=100.0)
    height: float = Field(..., gt=0.0, le=100.0)


class Torus(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["torus"]
    radius: float = Field(..., gt=0.0, le=100.0)
    tube: float = Field(..., gt=0.0, le=100.0)


class Capsule(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["capsule"]
    radius: float = Field(..., gt=0.0, le=100.0)
    length: float = Field(..., gt=0.0, le=100.0)


class Tube(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["tube"]
    path: list[Vec3] = Field(..., max_length=256, min_length=2)
    radius: float = Field(..., gt=0.0, le=100.0)
    closed: bool | None = False


class Lathe(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["lathe"]
    profile: list[Vec2] = Field(..., max_length=256, min_length=3)
    segments: int | None = Field(32, ge=3, le=256)


class Extrude(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["extrude"]
    shape: list[Vec2] = Field(..., max_length=256, min_length=3)
    depth: float = Field(..., gt=0.0, le=100.0)


class Geometry(
    RootModel[Sphere | Box | Cylinder | Cone | Torus | Capsule | Tube | Lathe | Extrude]
):
    root: Sphere | Box | Cylinder | Cone | Torus | Capsule | Tube | Lathe | Extrude = Field(
        ...,
        description="Closed vocabulary (spec §4). Ellipsoids are a sphere with non-uniform scale. CSG/booleans are out of scope for v1.",
        discriminator="type",
    )


class RotationItem(RootModel[float]):
    root: float = Field(..., ge=-360.0, le=360.0)


class ScaleItem(RootModel[float]):
    root: float = Field(..., gt=0.0, le=100.0)


class Transform(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    position: Vec3 | None = None
    rotation: list[RotationItem] | None = Field(
        None, description="Euler degrees, XYZ order.", max_length=3, min_length=3
    )
    scale: list[ScaleItem] | None = Field(None, max_length=3, min_length=3)


class Material(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    color: HexColor
    opacity: float | None = Field(1, ge=0.0, le=1.0)
    roughness: float | None = Field(0.5, ge=0.0, le=1.0)


class ChunkId(RootModel[str]):
    root: str = Field(..., max_length=64, min_length=1)


class Provenance(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    chunk_ids: list[ChunkId] = Field(..., max_length=32)
    evidence: str | None = Field(
        None,
        description="Quoted from the cited chunk. The validator matches it against the chunk text (D-008).",
        max_length=2000,
    )


class Alias(RootModel[str]):
    root: str = Field(..., max_length=80, min_length=1)


class Part(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: PartId
    name: str = Field(..., max_length=80, min_length=1)
    aliases: list[Alias] | None = Field(
        None, description="Drives part-scoped retrieval (D5).", max_length=16
    )
    instance_of: str | None = Field(
        None,
        description="Optional. Names the concept this part is an instance of. Parts sharing an instance_of are ONE retrieval target, and retrieval scopes on this rather than on the part's own name (D5). Present when a topic legitimately contains several of the same structure — an animal cell has many mitochondria — which would otherwise give each copy an identical, and therefore ambiguous, retrieval scope.",
        max_length=80,
        min_length=1,
    )
    parent_id: PartId | None = Field(
        None,
        description="Optional. The validator checks it resolves to an existing part and that the parent graph is acyclic.",
    )
    geometry: Geometry
    transform: Transform | None = None
    material: Material
    clip_exempt: bool | None = False
    importance: Literal["core", "secondary"] | None = Field(
        "core",
        description="Reserved in v1 — validated, but drives no behavior (D-006).",
    )
    provenance: Provenance


class Plane(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    normal: Vec3
    constant: float = Field(..., ge=-1000.0, le=1000.0)


class Cutaway(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    enabled: bool
    plane: Plane | None = None


class CameraHint(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    position: Vec3
    look_at: Vec3


class SceneSpec(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal["1.2"] = Field(
        ...,
        description="Bumped whenever the schema changes; the drift test (D7) keeps generated types in step.",
    )
    topic: str = Field(..., description="Stable slug, e.g. human_eye.", pattern="^[a-z0-9_]{2,64}$")
    title: str = Field(..., max_length=120, min_length=1)
    parts: list[Part] = Field(
        ...,
        description="Hard cap of 40 parts (spec §4). Uniqueness of ids is checked by the validator, not here.",
        max_length=40,
        min_length=1,
    )
    cutaway: Cutaway | None = None
    camera_hint: CameraHint | None = None
