"""3A — the deterministic half of structure extraction, and the guards on it.

Every rule is driven to its refusal at least once (R2). The model call is not tested here;
`decide()` is fed hand-written proposals, including ones built to be dropped, so the code
that DECIDES is proven without a key.
"""

from __future__ import annotations

import pytest

from aakar.evals.structures_eval import alias_coverage, score
from aakar.structures import (
    find_collisions,
    inflections,
    is_generic_mention,
    load_labels,
    mentions,
    normalise,
    occurrences,
    synonym_rejection,
)
from aakar.structures.extract import CollisionError, decide
from aakar.structures.verify import (
    confirm_naming_chunks,
    is_named_by_construction,
    singular_candidates,
)

CATEGORY = frozenset({"cell", "cells", "tissue", "membrane", "body", "pigment"})

CHAPTER = {
    "c01": ("541", "The outermost layer is the fibrous tunic, the white sclera and clear cornea."),
    "c04": ("542", "The iris is a smooth muscle that opens or closes the pupil."),
    "c06": ("543", "It is filled with a watery fluid called the aqueous humor."),
    "c07": ("544", "The photoreceptors (rods and cones) change their membrane potential."),
    "c09": ("545", "The rod-shaped outer segments of the rod photoreceptor contain discs."),
    "c10": ("546", "The axons of RGCs collect at the optic disc and leave as the optic nerve."),
}
TEXT = " ".join(t for _, t in CHAPTER.values())


# ------------------------------------------------------------------ the inflector


def test_english_and_classical_plurals_are_generated() -> None:
    assert {"retinas", "retinae"} <= inflections("retina")
    assert {"ganglia", "ganglions"} <= inflections("ganglion")
    assert "cortices" in inflections("cortex")
    assert "irides" in inflections("iris")
    assert "septa" in inflections("septum")


def test_spelling_variants_are_inflected_too() -> None:
    forms = inflections("aqueous humor")
    assert {"aqueous humour", "aqueous humours", "aqueous humors"} <= forms


def test_abbreviations_keep_case_and_take_a_plural() -> None:
    assert inflections("RGC") == {"RGC", "RGCs"}


def test_multiword_names_inflect_the_head_and_vary_the_join() -> None:
    forms = inflections("membrane-bound disc")
    assert {"membrane-bound discs", "membrane bound discs"} <= forms


def test_the_inflector_never_harvests_from_text() -> None:
    """The negative result that shaped D-063: `nervous` is not an alias of *optic nerve*
    and must not be generated by any rule, whatever the chapter says."""
    assert "nervous" not in inflections("optic nerve")
    assert "photosensitive" not in inflections("photoreceptor")


# ------------------------------------------------------------------ the matcher


def test_mentions_is_whole_word_and_case_insensitive() -> None:
    assert mentions("The Iris opens.", ["iris"])
    assert not mentions("an irishman", ["iris"])
    assert mentions("rod-shaped segments", ["rod"]), "a hyphen is a word boundary"


def test_hyphen_and_space_are_interchangeable_in_a_form() -> None:
    assert mentions("membrane bound discs", ["membrane-bound discs"])
    assert mentions("membrane-bound discs", ["membrane bound discs"])
    assert occurrences("disc, disc, discs", ["disc"]) == 2


# ------------------------------------------------------------------ the rules


def test_r1_excludes_a_bare_category_noun_seen_once() -> None:
    text = "the retina lacks the supporting cells and blood vessels"
    assert is_generic_mention(["supporting cells"], text, CATEGORY)


def test_r1_keeps_a_category_head_that_recurs_or_is_named() -> None:
    assert not is_generic_mention(["ciliary body"], "ciliary body, ciliary body", CATEGORY)
    assert not is_generic_mention(
        ["aqueous humor"], "a fluid called the aqueous humor", frozenset({"humor"})
    )


def test_r1_is_evaluated_over_surface_forms_not_the_canonical_name() -> None:
    """The case the rule had to be redefined for: `retinal ganglion cell` has a category
    head; `RGCs`, the only form the chapter uses, does not."""
    assert is_generic_mention(["retinal ganglion cell"], "one retinal ganglion cell", CATEGORY)
    assert not is_generic_mention(["RGCs"], "the axons of RGCs", CATEGORY)


def test_r1_asymmetry_is_a_known_property() -> None:
    """D-065: a non-category head is included at any count. Kept deliberately; this test
    pins the behaviour so a future 'fix' is a decision rather than a drift."""
    assert not is_generic_mention(["infoldings"], "the infoldings of the membrane", CATEGORY)
    assert is_generic_mention(["cell membrane"], "the infoldings of the cell membrane", CATEGORY)


def test_naming_constructions() -> None:
    assert is_named_by_construction("a fluid called the aqueous humor", ["aqueous humor"])
    assert is_named_by_construction("the neural tunic, or retina, which", ["retina"])
    assert not is_named_by_construction("The iris is a smooth muscle", ["smooth muscle"])


# ------------------------------------------------------------------ verifier, R3, guard


def test_the_verifier_drops_a_claimed_chunk_that_does_not_name_the_entity() -> None:
    texts = {k: t for k, (_, t) in CHAPTER.items()}
    confirmed, dropped = confirm_naming_chunks(["iris"], texts, ["c04", "c09"])
    assert confirmed == ("c04",)
    assert dropped == ("c09",), "the model said c09 names the iris; it does not"


def test_r3_finds_a_form_claimed_by_two_entities_by_any_route() -> None:
    hits = find_collisions({"cone": ["cone", "cones"], "conus": ["conus", "cones"]})
    assert [(c.form, c.entities) for c in hits] == [("cones", ("cone", "conus"))]
    assert find_collisions({"a": ["Membrane-bound disc"], "b": ["membrane bound disc"]})


def test_the_synonym_guard_rejects_the_dangerous_shapes_only() -> None:
    others = ["membrane-bound disc", "iris"]
    assert synonym_rejection("ciliary body", "body", others), "token of its own name"
    assert synonym_rejection("optic disc", "disc", others), "head of another entity"
    assert synonym_rejection("eye", "eye", others), "identical"
    assert synonym_rejection("eye", "eyeball", others) is None
    assert synonym_rejection("retinal ganglion cell", "RGC", others) is None


# ------------------------------------------------------------------ decide(), end to end


def _proposal(**overrides: object) -> dict[str, object]:
    base: dict[str, object] = {
        "name": "iris",
        "kind": "structure",
        "naming_chunk_ids": ["c04"],
        "surface_forms_in_text": ["iris"],
        "synonyms": [],
        "abbreviations": [],
        "modellable": True,
    }
    return {**base, **overrides}


def test_decide_keeps_a_real_entity_with_computed_chunks_and_aliases() -> None:
    result = decide([_proposal()], CHAPTER, category_nouns=CATEGORY)
    [ent] = result.entities
    assert ent.naming_chunks == ("c04",) and ent.pages == ("542",)
    assert "irides" in ent.all_forms, "rule inflections are emitted broadly"
    assert ent.claims_confirmed == ("c04",) and not ent.claims_dropped


def test_decide_drops_an_invented_entity() -> None:
    """The model names a structure no passage contains. It does not survive."""
    result = decide(
        [
            _proposal(
                name="lacrimal gland",
                naming_chunk_ids=["c01"],
                surface_forms_in_text=["lacrimal gland"],
            )
        ],
        CHAPTER,
        category_nouns=CATEGORY,
    )
    assert not result.entities
    assert result.dropped[0].rule == "not_named"
    assert ("lacrimal gland", "lacrimal gland") in result.unverifiable_forms


def test_decide_drops_a_kind_outside_the_vocabulary() -> None:
    result = decide([_proposal(kind="organ")], CHAPTER, category_nouns=CATEGORY)
    assert result.dropped[0].rule == "R0"


def test_decide_applies_r1_the_same_way_the_labels_do() -> None:
    proposal = _proposal(
        name="smooth muscle", naming_chunk_ids=["c04"], surface_forms_in_text=["smooth muscle"]
    )
    result = decide([proposal], CHAPTER, category_nouns=frozenset({"muscle"}))
    assert result.dropped[0].rule == "R1"


def test_decide_scores_the_models_chunk_claims_without_trusting_them() -> None:
    proposal = _proposal(naming_chunk_ids=["c04", "c09"])  # c09 does not name the iris
    [ent] = decide([proposal], CHAPTER, category_nouns=CATEGORY).entities
    assert ent.naming_chunks == ("c04",), "output uses the matcher, not the claim"
    assert ent.claims_dropped == ("c09",)


def test_decide_recovers_the_abbreviation_only_case() -> None:
    """THE hard case in the label set: the chapter writes only `RGCs`."""
    proposal = _proposal(
        name="retinal ganglion cell",
        kind="cell_type",
        naming_chunk_ids=["c10"],
        surface_forms_in_text=["RGCs"],
        abbreviations=["RGC"],
        modellable=False,
    )
    [ent] = decide([proposal], CHAPTER, category_nouns=CATEGORY).entities
    assert ent.naming_chunks == ("c10",)
    assert "RGCs" in ent.forms_in_chapter


def test_decide_refuses_the_whole_extraction_on_a_collision() -> None:
    """R3 as ruled: a defect, not a warning, and no winner is picked."""
    proposals = [
        _proposal(
            name="optic disc", naming_chunk_ids=["c10"], surface_forms_in_text=["optic disc"]
        ),
        _proposal(
            name="membrane-bound disc",
            naming_chunk_ids=["c09"],
            surface_forms_in_text=["discs"],
            synonyms=["optic disc"],  # a model synonym colliding with another entity
        ),
    ]
    with pytest.raises(CollisionError, match="optic disc"):
        decide(proposals, CHAPTER, category_nouns=CATEGORY)


# ------------------------------------------------------------------ the label set


def test_the_verified_label_set_loads_and_is_r3_clean() -> None:
    labels = load_labels()
    assert labels.verified and labels.verified_by
    assert len(labels.entities) == 28
    assert len(labels.modellable) == 18
    assert "retinal ganglion cell" in {e.name for e in labels.entities}


def test_the_label_set_commit_is_derived_not_typed() -> None:
    commit = load_labels().label_set_commit
    assert commit not in ("", "<the commit>") and len(commit) >= 7


# ------------------------------------------------------------------ scoring


def test_the_label_set_fed_back_as_an_extraction_scores_perfectly() -> None:
    """Guards the guard: a scorer that cannot recognise the ground truth is broken."""
    labels = load_labels()
    proposals = [
        {
            "name": lab.name,
            "kind": lab.kind,
            "naming_chunk_ids": list(lab.naming_chunks),
            "surface_forms_in_text": list(lab.surface_forms),
            "synonyms": [],
            "abbreviations": ["RGC"] if lab.name == "retinal ganglion cell" else [],
            "modellable": lab.modellable,
        }
        for lab in labels.entities
    ]
    from aakar.evals.golden import load_golden_set

    golden = load_golden_set()
    chunks = {c.chunk_id: (c.page_label, c.text) for c in golden.chunks}
    extraction = decide(proposals, chunks, category_nouns=labels.rules.category_nouns)
    scores = score(extraction, labels)
    assert scores.counts(modellable_only=False) == (28, 0, 0)
    assert scores.counts(modellable_only=True) == (18, 0, 0)
    assert all(not c.uncovered for c in alias_coverage(scores))


def test_scoring_sees_a_miss_a_duplicate_and_an_invention() -> None:
    labels = load_labels()
    from aakar.evals.golden import load_golden_set

    golden = load_golden_set()
    chunks = {c.chunk_id: (c.page_label, c.text) for c in golden.chunks}
    proposals = [
        _proposal(name="eye", naming_chunk_ids=["c01"], surface_forms_in_text=["eye"]),
        _proposal(name="eyeball", naming_chunk_ids=["c03"], surface_forms_in_text=["eyeball"]),
        _proposal(name="cornea", naming_chunk_ids=["c01"], surface_forms_in_text=["cornea"]),
    ]
    scores = score(decide(proposals, chunks, category_nouns=labels.rules.category_nouns), labels)
    tp, fp, fn = scores.counts(modellable_only=False)
    assert (tp, fp) == (2, 1), "eyeball is a duplicate of eye, not a new structure"
    assert fn == 26
    assert any("duplicate" in why for _, why in scores.false_positives)


def test_normalise_collapses_join_and_case() -> None:
    assert normalise("Membrane-Bound  Disc") == "membrane bound disc"


# ------------------------------------------------ the two measured alternatives (D-067)


def test_the_refined_guard_keeps_the_distinguishing_token_and_still_drops_the_category() -> None:
    """The first live run: the approved guard rejected `photoreceptor` for "Photoreceptor
    cell" because it is a token of its own name. Refined, only a CATEGORY token falls."""
    cats = frozenset({"cell", "body"})
    assert synonym_rejection("Photoreceptor cell", "photoreceptor", [], category_nouns=cats) is None
    assert synonym_rejection("ciliary body", "body", [], category_nouns=cats)
    # The approved guard, unchanged, still rejects both — the refinement is opt-in.
    assert synonym_rejection("Photoreceptor cell", "photoreceptor", [])


def test_the_head_noun_rule_is_name_choice_sensitive() -> None:
    """What the live run actually showed: even refined, `photoreceptor` falls to the OTHER
    rule once the model has named rods "Rod photoreceptor". The guard's outcome depends
    on which canonical name the model chose — a finding, recorded, not resolved here."""
    cats = frozenset({"cell"})
    reason = synonym_rejection(
        "Photoreceptor cell", "photoreceptor", ["Rod photoreceptor"], category_nouns=cats
    )
    assert reason and "head noun of another entity" in reason


def test_singular_recovery_is_corpus_checked() -> None:
    """`rods` (copied from c07) -> `rod` only because the chapter also says "rod
    photoreceptor"; `lens` -> `len` is proposed and never admitted because nothing in the
    chapter is a "len". Both halves are the corpus check doing its job."""
    assert "rod" in singular_candidates("rods")
    assert singular_candidates("lens") == ("len",)
    proposal = _proposal(
        name="Rod photoreceptor",
        kind="cell_type",
        naming_chunk_ids=["c07", "c09"],
        surface_forms_in_text=["rods"],
        modellable=False,
    )
    without = decide([proposal], CHAPTER, category_nouns=CATEGORY)
    with_ = decide([proposal], CHAPTER, category_nouns=CATEGORY, recover_singulars=True)
    assert "rod" not in {normalise(f) for f in without.entities[0].all_forms}
    assert "rod" in {normalise(f) for f in with_.entities[0].all_forms}

    lens = _proposal(
        name="crystalline lens", naming_chunk_ids=["c01"], surface_forms_in_text=["lens"]
    )
    chapter = {**CHAPTER, "c02": ("541", "the lens focuses light")}
    got = decide([lens], chapter, category_nouns=CATEGORY, recover_singulars=True)
    assert "len" not in {normalise(f) for f in got.entities[0].all_forms}
