// Cross-validator conformance corpus — zod side.
//
// The mirror of services/api/tests/test_conformance.py, over the same fixture files.
// `codegen-check` compares generated bytes, so a generator that faithfully emits a
// validator which accepts everything passes the drift test while validating nothing —
// D-015 was exactly that, and only a human reading the output caught it.
//
// Each fixture declares the outcome it expects. Both stacks assert against the same
// declaration, so a divergence fails whichever side is wrong.
import { readdirSync, readFileSync } from "node:fs";
import { basename, resolve } from "node:path";

import { describe, expect, it } from "vitest";

import { parseSceneSpec } from "./index";

const FIXTURES = resolve(__dirname, "../../../../packages/scenespec/fixtures");
const VALID_DIR = resolve(FIXTURES, "valid");
const INVALID_DIR = resolve(FIXTURES, "invalid");

const validFiles = readdirSync(VALID_DIR).filter((f) => f.endsWith(".json")).sort();
const invalidFiles = readdirSync(INVALID_DIR).filter((f) => f.endsWith(".json")).sort();

type InvalidFixture = {
  violates: string;
  pointer: string;
  target: string;
  note: string;
  spec: unknown;
};

function readJson(dir: string, file: string): unknown {
  return JSON.parse(readFileSync(resolve(dir, file), "utf8"));
}

describe("conformance corpus", () => {
  it("is present on both stacks", () => {
    expect(validFiles.length).toBeGreaterThanOrEqual(5);
    expect(invalidFiles.length).toBeGreaterThanOrEqual(50);
  });

  describe("valid fixtures are accepted", () => {
    for (const file of validFiles) {
      it(basename(file, ".json"), () => {
        const result = parseSceneSpec(readJson(VALID_DIR, file));
        if (!result.ok) throw new Error(`zod rejected a valid fixture:\n${result.errors.join("\n")}`);
        expect(result.ok).toBe(true);
      });
    }
  });

  describe("invalid fixtures are rejected", () => {
    for (const file of invalidFiles) {
      const fixture = readJson(INVALID_DIR, file) as InvalidFixture;
      it(`${basename(file, ".json")} — ${fixture.violates}`, () => {
        const result = parseSceneSpec(fixture.spec);
        if (result.ok) {
          throw new Error(
            `zod ACCEPTED a fixture that must be rejected.\n` +
              `  constraint: ${fixture.pointer} ${fixture.violates}\n` +
              `  target:     ${fixture.target}\n` +
              `  note:       ${fixture.note}`,
          );
        }
        expect(result.errors.length).toBeGreaterThan(0);
      });
    }
  });

  it("a vacuous validator would fail this corpus", () => {
    // Guards the guard: states the D-015 failure mode as its own assertion, so the
    // corpus cannot be quietly reduced to documents that are all valid anyway.
    const accepted = invalidFiles.filter(
      (file) => parseSceneSpec((readJson(INVALID_DIR, file) as InvalidFixture).spec).ok,
    );
    expect(accepted, `zod accepted ${accepted.length} invalid fixtures`).toEqual([]);
  });
});
