// Public surface for the SceneSpec types. Import from here, never from ./generated
// directly — that file is regenerated by `make codegen` and must stay replaceable.
import type { z } from "zod";

import { type ReferentialError, validateReferential } from "@scenespec/referential";

import { sceneSpecSchema } from "./generated";

export { sceneSpecSchema };

/**
 * The schema_version this build targets. Declared once: three test files had it
 * hardcoded and the 1.0 -> 1.1 bump broke all three. `generated.test.ts` asserts this
 * matches the schema's own `const`, so it cannot drift silently.
 */
export const SCHEMA_VERSION = "1.1";

export type SceneSpec = z.infer<typeof sceneSpecSchema>;
export type Part = SceneSpec["parts"][number];

export type { ReferentialError };

export type ParseIssue = { code: string; path: string; message: string };

export type ParseResult =
  | { ok: true; spec: SceneSpec }
  | { ok: false; errors: string[]; issues: ParseIssue[] };

/**
 * Parse **and** validate referentially.
 *
 * The three constraints JSON Schema cannot express — unique part ids, parent refs
 * resolving, an acyclic parent graph — used to run only inside `compile()`. That meant
 * storage, the API, and anything parsing without rendering skipped them; Phase 3's
 * generator parses and stores server-side and only renders when the critic runs, so a
 * structurally broken spec would have arrived at the repair loop as a render failure
 * rather than as a diagnosable validation error.
 *
 * Referential checks run only once the schema parse succeeds — they need `parts` to be
 * the right shape before they can say anything useful about it.
 */
export function parseSceneSpec(input: unknown): ParseResult {
  const result = sceneSpecSchema.safeParse(input);
  if (!result.success) {
    const issues: ParseIssue[] = result.error.issues.map((i) => ({
      code: `schema:${i.code}`,
      path: i.path.join("."),
      message: i.message,
    }));
    return { ok: false, errors: issues.map(format), issues };
  }

  const spec = result.data as SceneSpec;
  const referential = validateReferential(spec);
  if (referential.length > 0) {
    return { ok: false, errors: referential.map(format), issues: referential };
  }

  return { ok: true, spec };
}

function format(issue: ParseIssue): string {
  return issue.path ? `${issue.path}: ${issue.message}` : issue.message;
}
