// Public surface for the SceneSpec types. Import from here, never from ./generated
// directly — that file is regenerated by `make codegen` and must stay replaceable.
import type { z } from "zod";

import { sceneSpecSchema } from "./generated";

export { sceneSpecSchema };

export type SceneSpec = z.infer<typeof sceneSpecSchema>;
export type Part = SceneSpec["parts"][number];

export type ParseResult =
  | { ok: true; spec: SceneSpec }
  | { ok: false; errors: string[] };

/**
 * Schema-level parse. The three constraints JSON Schema cannot express — unique part
 * ids, parent refs resolving, and the parent graph being acyclic — belong to the
 * deterministic validator arriving with the compiler in Phase 1.
 */
export function parseSceneSpec(input: unknown): ParseResult {
  const result = sceneSpecSchema.safeParse(input);
  if (result.success) return { ok: true, spec: result.data as SceneSpec };
  return {
    ok: false,
    errors: result.error.issues.map((i) =>
      i.path.length ? `${i.path.join(".")}: ${i.message}` : i.message,
    ),
  };
}
