#!/usr/bin/env bash
# Regenerates both generated type files from scenespec.schema.json (D7).
# Never hand-edit the outputs; `make codegen-check` fails the build if they are stale.
set -euo pipefail
cd "$(dirname "$0")/../.."

node packages/scenespec/codegen.mjs

HEADER='# GENERATED by `make codegen` from packages/scenespec/scenespec.schema.json (D7).
# Do not edit. CI fails if this file is stale.'

cd services/api
uv run datamodel-codegen \
  --input ../../packages/scenespec/scenespec.schema.json \
  --input-file-type jsonschema \
  --output-model-type pydantic_v2.BaseModel \
  --disable-timestamp \
  --use-standard-collections \
  --use-union-operator \
  --field-constraints \
  --enum-field-as-literal all \
  --custom-file-header "$HEADER" \
  --output aakar/scenespec/generated.py 2>&1 | grep -v 'FutureWarning\|warn_deprecated' || true

# datamodel-codegen emits single quotes; `ruff format` (which CI also runs) rewrites them
# to double. Without this step codegen is not idempotent and the D7 drift job fails on
# every run for a reason that has nothing to do with the schema.
uv run ruff format aakar/scenespec/generated.py >/dev/null

echo "pydantic -> services/api/aakar/scenespec/generated.py"
