// Codegen for D7: scenespec.schema.json is the single source of truth.
// Emits zod (web) and pydantic (api). Never hand-edit the outputs — `make codegen`
// regenerates them and CI fails the build if they are stale.
//
// json-schema-to-zod does not follow $ref into $defs (it emits z.any(), which would
// silently validate nothing), so the schema is fully dereferenced first. The schema has
// no cycles — parent_id is a string, not a $ref to Part — so inlining always terminates.

import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "../..");
const schemaPath = resolve(here, "scenespec.schema.json");
const zodOut = resolve(repoRoot, "apps/web/src/scenespec/generated.ts");

const schema = JSON.parse(readFileSync(schemaPath, "utf8"));

function deref(node, defs, seen = new Set()) {
  if (Array.isArray(node)) return node.map((n) => deref(n, defs, seen));
  if (node === null || typeof node !== "object") return node;

  if (typeof node.$ref === "string") {
    const name = node.$ref.replace("#/$defs/", "");
    if (!(name in defs)) throw new Error(`unresolved $ref: ${node.$ref}`);
    if (seen.has(name)) throw new Error(`cyclic $ref through ${name}`);
    const { $ref, ...siblings } = node;
    return { ...deref(defs[name], defs, new Set([...seen, name])), ...deref(siblings, defs, seen) };
  }

  return Object.fromEntries(Object.entries(node).map(([k, v]) => [k, deref(v, defs, seen)]));
}

const defs = schema.$defs ?? {};
const { $defs, $id, ...root } = schema;
const flat = deref(root, defs);

const tmp = resolve(repoRoot, "node_modules/.cache/scenespec.deref.json");
mkdirSync(dirname(tmp), { recursive: true });
writeFileSync(tmp, JSON.stringify(flat, null, 2));

// Resolve the generator's real JS entrypoint and run it under this node binary. The
// node_modules/.bin shim is a bare extensionless file on Windows, which execFileSync
// cannot spawn (ENOENT) — going through the entrypoint keeps codegen portable.
const requireFrom = createRequire(resolve(repoRoot, "apps/web/package.json"));
// The package's "exports" map hides ./package.json, so walk up from the module entry
// to the package root rather than resolving the manifest by subpath.
// Nested dist/ folders carry their own {"type":"commonjs"} package.json, so walk up to
// the first manifest that actually declares "bin".
function packageBin(fromEntry) {
  let dir = dirname(fromEntry);
  for (;;) {
    const manifest = resolve(dir, "package.json");
    if (existsSync(manifest)) {
      const { bin } = JSON.parse(readFileSync(manifest, "utf8"));
      if (typeof bin === "string") return resolve(dir, bin);
    }
    const up = dirname(dir);
    if (up === dir) throw new Error(`no "bin" found above ${fromEntry}`);
    dir = up;
  }
}
const cli = packageBin(requireFrom.resolve("json-schema-to-zod"));
const body = execFileSync(process.execPath, [cli, "-i", tmp, "-n", "sceneSpecSchema"], {
  encoding: "utf8",
});

const header = `// GENERATED by packages/scenespec/codegen.mjs from scenespec.schema.json (D7).
// Do not edit. Run \`make codegen\`; CI fails if this file is stale.
`;

writeFileSync(zodOut, header + body.replace(/\r\n/g, "\n").trimEnd() + "\n");
console.log(`zod   -> ${zodOut}`);
